-- DropIndex
DROP INDEX "user_roleId_key";

-- AlterTable
ALTER TABLE "role" ALTER COLUMN "createdDate" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "user" ALTER COLUMN "active" DROP NOT NULL,
ALTER COLUMN "active" SET DEFAULT true,
ALTER COLUMN "createDate" SET DEFAULT CURRENT_TIMESTAMP;
